import crypto from 'node:crypto';
export const journeys={startup:'Inicialização lenta',update:'Windows Update com falha',apps:'Aplicativos travando',network:'Problemas de rede',integrity:'Integridade do Windows'};
export function symptomRoute(text){
 if(typeof text!=='string'||text.length>1000)throw Error('Descreva o sintoma em até 1.000 caracteres.');
 const normalized=text.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
 const patterns={startup:/inici|boot|ligar|liga lento/,update:/update|atualiza/,apps:/trava|aplicativo|programa|fecha sozinho|crash/,network:/internet|rede|wi.?fi|dns|vpn|conexa/,integrity:/corromp|integridade|sfc|dism|arquivo do sistema/};
 const matches=Object.entries(patterns).filter(([,p])=>p.test(normalized)).map(([id])=>id);
 return {journeys:matches.length?matches:Object.keys(journeys),method:'Regras locais por palavras do sintoma; não usa IA remota.',confidence:matches.length===1?'média':'baixa',note:'Sugestão de investigação; não identifica a causa e não executa comandos.'};
}
const section=(raw,key)=>raw[key]?.status==='available'?raw[key].data:null;
export function diagnose(raw,{extended=false}={}){
 const findings=[];const at=raw.at||new Date().toISOString();
 const add=(id,category,kind,severity,title,evidence,hypothesis,confidence,tests,actions=[])=>findings.push({id,category,kind,severity,title,evidence,at,hypothesis,confidence,tests,actions});
 for(const key of ['boot','events','services','network','performance','startup'])if(raw[key]?.status!=='available')add('unavailable-'+key,key==='boot'?'startup':key==='events'?'apps':key==='services'?'update':key==='performance'?'startup':key,'unavailable','info','Coleta indisponível: '+key,[raw[key]?.reason||'Não coletado'],'Sem evidência suficiente para concluir.','não aplicável',['Verifique permissões e repita a coleta.']);
 const boot=section(raw,'boot')||[];const latest=boot[0];
 if(latest?.durationMs>60000)add('boot-slow','startup','confirmed','attention','Inicialização acima de 60 segundos nesta medição',[`Evento de boot em ${latest.at}: ${(latest.durationMs/1000).toFixed(1)} s.`],'A demora foi medida; programas de inicialização são apenas candidatos, não causas confirmadas.','alta para duração; baixa para causa',['Compare pelo menos três inicializações equivalentes.','Revise uma entrada por vez.'],['startupDisable']);
 const startup=section(raw,'startup')||[];
 if(startup.length)add('startup-review','startup','preventive','info','Entradas de inicialização disponíveis para revisão',[`${startup.length} entradas na chave Run do usuário.`],'A quantidade de entradas, isoladamente, não comprova lentidão.','baixa',['Identifique o aplicativo antes de desativá-lo.'],startup.some(x=>!x.protected)?['startupDisable']:[]);
 const events=section(raw,'events')||[];
 const updates=events.filter(e=>e.provider==='Microsoft-Windows-WindowsUpdateClient'&&[20,25,31].includes(e.id));
 if(updates.length)add('update-failures','update','confirmed','attention','Falhas registradas pelo Windows Update',updates.slice(0,4).map(e=>`${e.at}: evento ${e.id}`),'A causa pode envolver conectividade, serviço ou integridade; o evento não prova qual.','alta para ocorrência; baixa para causa',['Verifique reinício pendente e conectividade.','Consulte novamente o Windows Update.'],['updateRetry','integrityScan']);
 const services=section(raw,'services')||[];
 if(!updates.length)add('update-context','update','information','info','Nenhuma falha de atualização identificada na janela disponível',['Consulta limitada aos eventos coletados.'],'Ausência de eventos não confirma funcionamento de todas as atualizações.','baixa',['Se o sintoma persiste, abra Windows Update e registre o código exibido.'],['openUpdate']);
 if(services.some(s=>s.name==='wuauserv'&&s.startMode==='Disabled'))add('update-disabled','update','information','attention','Serviço de atualização desabilitado',['wuauserv com inicialização desabilitada.'],'Pode ser uma política administrativa. Nenhuma política será alterada.','média',['Consulte o administrador da máquina.'],['openUpdate']);
 const appEvents=events.filter(e=>['Application Error','Application Hang','Windows Error Reporting'].includes(e.provider)&&[1000,1001,1002].includes(e.id));
 if(appEvents.length)add('app-crashes','apps',appEvents.length>=2?'confirmed':'information',appEvents.length>=2?'attention':'info','Falhas de aplicativos registradas',appEvents.slice(0,6).map(e=>`${e.at}: ${e.provider}, evento ${e.id}${e.application?' — '+e.application:''}`),'Proximidade com uma atualização não comprova causalidade.','alta para ocorrência; baixa para causa',['Reproduza o sintoma e registre se o aplicativo voltou a funcionar.','Use Reparar do próprio aplicativo, quando disponível.'],['openApps','integrityScan']);
 const net=section(raw,'network');
 if(!appEvents.length)add('app-context','apps','information','info','Nenhum travamento identificado na janela disponível',['Consulta limitada a eventos 1000, 1001 e 1002.'],'O aplicativo pode falhar sem registrar um desses eventos.','baixa',['Reproduza o problema e revise as opções oficiais do aplicativo.'],['openApps']);
 if(net){
  add('network-context','network','information','info','Configuração local de rede registrada',['DHCP, presença de DNS, proxy e indícios de VPN coletados.'],'O diagnóstico não modifica a conectividade.','não aplicável',['Use o teste autorizado para obter amostras de conectividade.'],['networkRetest']);
  if(net.vpnDetected||net.proxyEnabled||net.pacPresent)add('network-policy','network','information','info','VPN ou proxy detectado',[`VPN: ${!!net.vpnDetected}; proxy: ${!!net.proxyEnabled}; PAC: ${!!net.pacPresent}.`],'VPN/proxy pode ser necessário à organização; não é classificado como falha.','média',['Compare o sintoma com o administrador; não desconecte VPN corporativa sem autorização.'],['networkRetest']);
  if(!net.adapters?.some(a=>a.status==='Up'))add('network-link','network','confirmed','attention','Nenhuma interface de rede ativa na leitura',['Adaptadores locais sem estado Up.'],'Verifique conexão física, Wi-Fi ou modo avião.','alta',['Confira o cabo ou Wi-Fi e repita o diagnóstico.'],['networkRetest']);
  if(net.probe){const p=net.probe;
   if(p.dnsStatus==='failed')add('network-dns','network','hypothesis','attention','Consulta DNS de teste falhou',['Não foi possível resolver www.microsoft.com com a configuração atual.'],'DNS, VPN, proxy ou política da rede pode impedir o teste.','média',['Compare com um destino permitido pela organização.'],['networkRetest']);
   if(p.gateway?.sent&&p.gateway.received===0)add('network-gateway','network','hypothesis','attention','Gateway não respondeu ao teste ICMP',[`${p.gateway.received}/${p.gateway.sent} respostas.`],'Pode haver falha local ou bloqueio de ICMP; não comprova ausência de internet.','baixa',['Verifique a rede local e as políticas de ICMP.'],['networkRetest']);
   if(p.target?.sent&&p.target.received<p.target.sent)add('network-loss','network','hypothesis','attention','Respostas ICMP ausentes no destino de teste',[`${p.target.received}/${p.target.sent} respostas de www.microsoft.com.`],'ICMP pode estar bloqueado ou limitado; não localiza sozinho falha no provedor.','baixa',['Repita a medição e compare com o gateway.'],['networkRetest']);
  }else add('network-not-probed','network','information','info','Conectividade externa ainda não testada',['Coleta local sem sondagem externa.'],'É necessário consentimento para DNS e quatro pings por destino.','não aplicável',['Autorize o teste de rede, se permitido.'],['networkRetest']);
 }
 if(raw.restartPending)add('restart-pending','integrity','confirmed','attention','Reinicialização pendente',['Marcador de manutenção pendente no Windows.'],'A manutenção incompleta pode interferir nos resultados; não prova corrupção.','alta',['Salve o trabalho e reinicie pelo Windows quando for conveniente.']);
 if(raw.integrity?.state==='Repairable')add('integrity-corruption','integrity','confirmed','attention','Corrupção reparável no repositório de componentes',[`DISM: ${raw.integrity.state}, verificado em ${raw.integrity.at}.`],'DISM confirmou corrupção nos componentes; sintomas de aplicativos ainda precisam de teste.','alta',['Após o reparo, repetir DISM e SFC.'],raw.restartPending?[]:['integrityRepair']);
 else if(raw.integrity?.state==='NonRepairable')add('integrity-unrepairable','integrity','confirmed','high','DISM indica imagem não reparável',['ImageHealthState: NonRepairable.'],'O reparo automático deste catálogo não é elegível.','alta',['Preserve dados e procure recuperação oficial do Windows.']);
 else add('integrity-check','integrity',raw.integrity?.state==='Healthy'?'information':'unavailable','info',raw.integrity?.state==='Healthy'?'Componentes íntegros na verificação registrada':'Integridade exige uma verificação específica',[raw.integrity?.state||'Não examinada por DISM nesta coleta.'],'Eventos de erro não bastam para afirmar corrupção.','não aplicável',['Execute a verificação específica com autorização administrativa.'],raw.restartPending?[]:['integrityScan']);
 const perf=section(raw,'performance');
 if(perf?.samples?.length>=3){const samples=perf.samples;if(samples.every(x=>x.cpuPercent>=85))add('cpu-pressure','startup','hypothesis','attention','CPU elevada em todas as amostras',samples.map(x=>`${x.cpuPercent}%`),'A janela curta pode refletir uma tarefa temporária.','média',['Repita durante o sintoma; confira os processos.']);if(samples.every(x=>x.availableMB<1024))add('memory-pressure','apps','hypothesis','attention','Pouca memória disponível nas amostras',samples.map(x=>`${x.availableMB} MiB disponíveis`),'Pode haver pressão de memória; liberar RAM artificialmente não resolve a causa.','média',['Revise os aplicativos em uso e repita.']);}
 if(raw.os&&(raw.os.build<26100||raw.os.productType!==1||raw.os.nativeArchitecture!=='AMD64')){for(const f of findings)f.actions=f.actions.filter(a=>!['startupDisable','integrityScan','integrityRepair','updateRetry'].includes(a));add('compatibility','integrity','information','info','Reparos restritos pela compatibilidade desta prévia',[`Sistema coletado: ${raw.os.caption||'Windows'}, build ${raw.os.build}.`],'Procedimentos de alteração exigem Windows 11 cliente x64, build 26100 ou superior, em edição prevista no catálogo.','não aplicável',['Diagnóstico, histórico e reversão suportada continuam disponíveis.']);}
 const timeline=extended?events.slice(0,240).map(e=>({...e,relationship:'Ocorrência observada; correlação temporal não confirma causa.'})):[];
 return {id:crypto.randomUUID(),schema:1,at,windowHours:raw.windowHours,mode:extended?'extended':'basic',journeys,findings,timeline,raw,limitations:['Medições curtas e eventos históricos não estabelecem causalidade.','Coleta sob demanda; sem monitoramento contínuo, reparo de hardware ou IA remota.']};
}
