import fs from 'node:fs/promises';
import path from 'node:path';
const source=path.join(process.env.LOCALAPPDATA,'VimakaWindowsCare','data','comparison.json');
const {before,current,notes}=JSON.parse((await fs.readFile(source,'utf8')).replace(/^\uFEFF/,''));
if(!before||!current)throw Error('Execute um diagnóstico antes de exportar.');
const esc=s=>String(s??'Não medido').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rows=[['Entradas de inicialização',before.startup.length,current.startup.length],['Memória livre (GB)',before.freeGB,current.freeGB],['Serviços Remojo',before.remojo,current.remojo],['Plano de energia',before.power,current.power],['Momento da leitura',before.at,current.at]];
const html=`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Vimaka · Antes e depois</title><style>body{font:16px/1.7 'Segoe UI',sans-serif;background:#fdfdfd;color:#0f1729;padding:30px}main{max-width:1000px;margin:auto;background:white;padding:40px;border-radius:16px}h1{font-size:38px}table{border-collapse:collapse;width:100%;font-size:15px}td,th{padding:15px;border-bottom:1px solid #e7ebf1;text-align:left;overflow-wrap:anywhere}p{color:#64748b}.note{background:#edf3ff;padding:18px;border-left:4px solid #0059ff}@media print{body{padding:0;background:white}main{padding:0}}</style></head><body><main><p>VIMAKA SISTEMAS INTELIGENTES · WINDOWS CARE</p><h1>Antes e depois, com evidências.</h1><table><thead><tr><th>Indicador</th><th>Antes</th><th>Agora</th></tr></thead><tbody>${rows.map(r=>'<tr>'+r.map(c=>'<td>'+esc(c)+'</td>').join('')+'</tr>').join('')}</tbody></table><p class="note">A memória livre varia com os aplicativos abertos. Estas leituras não constituem benchmark nem comprovam aceleração. Tempos de boot, CPU e velocidade de internet não foram comparados de forma controlada.</p><p>${esc(notes||'Referência coletada no primeiro diagnóstico deste aplicativo.')}</p><h2>Como interpretar</h2><p>Compare as entradas de inicialização e o plano de energia com o histórico de ações. Serviços Remojo ausentes não significam desinstalação completa do aplicativo. Um valor menor de memória livre não prova perda de desempenho.</p><p>Relatório local. Revise antes de compartilhar. Pode ser impresso como PDF pelo navegador.</p></main></body></html>`;
const output=path.resolve(process.argv[2]||'Vimaka-antes-e-depois.html');await fs.writeFile(output,html);console.log(output);
